### ISSUE TITLE
CADSys42 License

### ISSUE THREAD

**Issue by mdadali** [michalgw/CADSys42#6]
Dear developers,

I’ve contacted Piero Valagussa, the author of CADSys42. He is willing to switch the library to an MIT or GPL license. Since he doesn’t have his own Git repository, would you be able to update the license in your repository if Piero contacts you?

Thank you for your support!

Best regards,
Mustafa (mdadali@yahoo.de)

**Comment by michalgw** [comment]
Hello Mustafa! 
I am glad to see this news. Of course I will change the license to the indicated one. I noticed that you are actively using this library in your project so maybe you will accept an invitation to the CADSys repository? Or if you prefer you can send a pull request with your changes. Unfortunately, I am currently working on another project but I intend to return to a project using the CADSys library in the future.

Regards, Michał.

**Comment by mdadali** [comment]
Hello Michal,

Piero's wish is to use the MIT License. It would be great if you could take this into consideration, please. I will definitely upload my version of CADSys4 and LazTTF2Vector once I have cleaned up the source code a bit. I will need a few days for that. I'm already looking forward to the invitation to the CADSys repository. Just please make sure everything is backed up well, as I have no experience with GitHub. I'll get in touch in the next few days. If you change the license file, please let me know so I can inform Piero. He will also be happy about it. Or are you already in contact with him?

Best regards,
Mustafa.

**Comment by mdadali** [comment]
Mail from Piero:
"Great news, Mustafa.
I wish you all the best and success, and I will follow the repository as best as I can in the future.
Thank you for keeping an old piece of my work alive. 🙏

Piero Valagussa"

**Comment by michalgw** [comment]
Hi.
I just received confirmation from Piero and changed the license to MIT.
I have sent you an invitation to the repository.
Thanks again.

**Comment by mdadali** [comment]
Hi,
Thank you!

**Comment by mdadali** [comment]
Hello Michal,

I've added the following procedures/tasks to the unit CS4Tasks::

//added
procedure CopyToCADClipboard(AIterator: TGraphicObjIterator);
procedure Inverse(APrimitive2D: TPrimitive2D);
procedure InverseEllipticalArc2D(AArcD: TEllipticalArc2D);
procedure Reverse(APrimitive2D: TPrimitive2D);
procedure ReverseEllipticalArc2D(var AArcD: TEllipticalArc2D);
procedure ReverseLine2D(ALine2D: TLine2D);
procedure ReverseOutLine2D(AOutLine2D: TOutLine2D);


type
TCAD2DDeleteObjects = class(TCADState)
TCAD2DScaleObjects = class(TCADState)
TCAD2DMirrorXObjects = class(TCADState)
TCAD2DMirrorYObjects = class(TCADState)
TCAD2DExplodeObjects = class(TCADState)
TCAD2DReverse = class(TCADState)
TCAD2DInverse = class(TCADState)
TCAD2DCreateSourceBlock = class(TCADState)
TCAD2DBringToFront = class(TCADState)
TCAD2DSendToBack = class(TCADState)
TCAD2DBringForward = class(TCADState)
TCAD2DSendBackwards = class(TCADState)
TCAD2DAlignLeft = class(TCADState)
TCAD2DAlignTop = class(TCADState)
TCAD2DAlignRight = class(TCADState)
TCAD2DAlignBottom = class(TCADState)
TCAD2DCopyObjectsToCADClipboard = class(TCADState)
TCAD2DCutObjects = class(TCADState)
TCAD2DPasteObjects = class(TCADState)
TCAD2DMakeContainer = class(TCADState)
TCAD2DOffsetObjects = class(TCADState)


//Clipper (Clipper-Library from Angus Jonson)
TCAD2DClipperIntersectionObjects = class(TCADState)
TCAD2DClipperXOrObjects = class(TCADState)
TCAD2DClipperDifferenceObjects = class(TCADState)
TCAD2DClipperOffsetObjects = class(TCADState)
//End-Clipper


 I've also added multiple new procedures and functions to the CADSys4 unit and made modifications to the file format. However, I’ve kept the library structure intact—it's still clean and readable as before.

I don’t think I can synchronize my version with yours immediately. For now, I’ve created my own Git repository where you can check out and integrate useful features. I'm not finished yet, but I’ll contact you again once I complete my changes, and hopefully, we can integrate everything into a unified repository later.

Feel free to use my LazTTF2Vector tool, which I’ve also integrated into LazCAD.

Here is my Git repository:  https://github.com/mdadali/LazCAD
Binarys:         Linux 64-bit: https://www.hackcad.com/maindownloads/LazCAD-x86_64-linux.zip
                Windows 64-bit: https://www.hackcad.com/maindownloads/LazCAD-x86_64-win64.zip


Best regards,
Mustafa
